all:
  hosts:
    winhost:
      ansible_host: 192.168.33.10
      ansible_port: 5985
      ansible_user: Administrator
      ansible_password: vagrant
      ansible_connection: winrm
      ansible_winrm_transport: basic
  children:
    ungrouped:
      wintest: